import { SensorConfig, SensorType, WaterContext } from '../types';

export const SENSOR_CONFIGS: Record<SensorType, SensorConfig> = {
  pH: {
    type: 'pH',
    name: 'pH Level',
    unit: 'pH',
    minNormal: 6.5,
    maxNormal: 8.5,
    minWarning: 6.0,
    maxWarning: 9.0,
    minPhysical: 0.0,
    maxPhysical: 14.0,
    step: 0.01,
    pin: 'GPIO 36 (ADC1_CH0)',
    iconName: 'Droplet',
    description: 'Measures the acidity or alkalinity of the water on a logarithmic scale.',
    standardsGuide: 'WHO & EPA recommend 6.5 – 8.5 for potable drinking water; >8.5 causes scaling, <6.5 causes pipe leaching.'
  },
  turbidity: {
    type: 'turbidity',
    name: 'Turbidity',
    unit: 'NTU',
    minNormal: 0.0,
    maxNormal: 4.0,
    minWarning: 0.0,
    maxWarning: 10.0,
    minPhysical: 0.0,
    maxPhysical: 1000.0,
    step: 0.1,
    pin: 'GPIO 39 (ADC1_CH3)',
    iconName: 'EyeOff',
    description: 'Measures cloudiness caused by suspended particles, colloids, and silt.',
    standardsGuide: 'EPA/WHO target is < 1.0 NTU (acceptable up to 5.0 NTU in distribution networks).'
  },
  temperature: {
    type: 'temperature',
    name: 'Water Temperature',
    unit: '°C',
    minNormal: 15.0,
    maxNormal: 25.0,
    minWarning: 10.0,
    maxWarning: 32.0,
    minPhysical: 0.0,
    maxPhysical: 80.0,
    step: 0.1,
    pin: 'GPIO 4 (DS18B20 OneWire)',
    iconName: 'Thermometer',
    description: 'Water temperature affects biological activity, gas solubility, and chemical reaction rates.',
    standardsGuide: 'Typical safe ambient distribution is 15°C – 25°C. Temperatures >25°C accelerate bacterial growth (e.g., Legionella).'
  },
  tds: {
    type: 'tds',
    name: 'Total Dissolved Solids',
    unit: 'ppm',
    minNormal: 50,
    maxNormal: 300,
    minWarning: 30,
    maxWarning: 600,
    minPhysical: 0,
    maxPhysical: 2000,
    step: 1,
    pin: 'GPIO 34 (ADC1_CH6)',
    iconName: 'Layers',
    description: 'Measures combined content of all inorganic and organic substances in molecular/ionized form.',
    standardsGuide: 'WHO standard: <300 ppm Excellent, 300-600 ppm Good, 600-900 ppm Fair, >1000 ppm Unacceptable.'
  },
  conductivity: {
    type: 'conductivity',
    name: 'Electrical Conductivity',
    unit: 'µS/cm',
    minNormal: 100,
    maxNormal: 600,
    minWarning: 50,
    maxWarning: 1200,
    minPhysical: 0,
    maxPhysical: 5000,
    step: 1,
    pin: 'GPIO 35 (ADC1_CH7)',
    iconName: 'Zap',
    description: 'Electrical conductance measuring dissolved mineral salts and electrolyte content.',
    standardsGuide: 'Typical freshwater ranges between 100 – 1000 µS/cm; sudden spikes indicate industrial/saline infiltration.'
  },
  dissolved_oxygen: {
    type: 'dissolved_oxygen',
    name: 'Dissolved Oxygen',
    unit: 'mg/L',
    minNormal: 6.5,
    maxNormal: 12.0,
    minWarning: 4.5,
    maxWarning: 14.0,
    minPhysical: 0.0,
    maxPhysical: 20.0,
    step: 0.1,
    pin: 'GPIO 32 (Galvanic DO probe)',
    iconName: 'Wind',
    description: 'Amount of free, non-compound oxygen present in water vital for aquatic health.',
    standardsGuide: '>6.5 mg/L indicates clean, healthy water. <4.0 mg/L causes hypoxia and fish suffocation in aquaculture.'
  },
  orp: {
    type: 'orp',
    name: 'Oxidation-Reduction Potential',
    unit: 'mV',
    minNormal: 250,
    maxNormal: 750,
    minWarning: 200,
    maxWarning: 850,
    minPhysical: -1000,
    maxPhysical: 1000,
    step: 1,
    pin: 'GPIO 33 (ADC1_CH5)',
    iconName: 'ShieldAlert',
    description: 'Measures water cleanliness and its capacity to break down chemical and biological contaminants.',
    standardsGuide: 'Potable water disinfection requires >650 mV ORP to neutralize harmful pathogens rapidly.'
  },
  water_level: {
    type: 'water_level',
    name: 'Reservoir Water Level',
    unit: 'm',
    minNormal: 2.0,
    maxNormal: 4.8,
    minWarning: 1.0,
    maxWarning: 5.2,
    minPhysical: 0.0,
    maxPhysical: 6.0,
    step: 0.01,
    pin: 'GPIO 13/14 (Ultrasonic/Submersible 4-20mA)',
    iconName: 'Gauge',
    description: 'Ultrasonic or hydrostatic measurement of tank/reservoir fill depth.',
    standardsGuide: 'Standard operational tank operating range 2.0m to 4.8m; below 1.0m triggers dry-run pump safety shutdown.'
  },
  chlorine: {
    type: 'chlorine',
    name: 'Free Residual Chlorine',
    unit: 'mg/L',
    minNormal: 0.5,
    maxNormal: 2.0,
    minWarning: 0.2,
    maxWarning: 3.5,
    minPhysical: 0.0,
    maxPhysical: 5.0,
    step: 0.05,
    pin: 'GPIO 25 (Amperometric probe)',
    iconName: 'Sparkles',
    description: 'Concentration of free residual disinfectant available to neutralize pathogens.',
    standardsGuide: 'WHO guideline at point of delivery is 0.2 – 0.5 mg/L, municipal tank residual 0.5 – 2.0 mg/L.'
  },
  nitrate: {
    type: 'nitrate',
    name: 'Nitrate (NO3-)',
    unit: 'mg/L',
    minNormal: 0.0,
    maxNormal: 10.0,
    minWarning: 0.0,
    maxWarning: 25.0,
    minPhysical: 0.0,
    maxPhysical: 100.0,
    step: 0.1,
    pin: 'GPIO 26 (Ion-Selective Electrode)',
    iconName: 'AlertCircle',
    description: 'Nutrient compound originating from fertilizer agricultural runoff and organic waste decay.',
    standardsGuide: 'EPA Maximum Contaminant Level (MCL) is 10 mg/L (as Nitrogen) or 50 mg/L (as NO3).'
  }
};

export const CONTEXT_THRESHOLDS: Record<WaterContext, Partial<Record<SensorType, { min: number; max: number }>>> = {
  drinking: {
    pH: { min: 6.5, max: 8.5 },
    turbidity: { min: 0.0, max: 4.0 },
    tds: { min: 50, max: 500 },
    temperature: { min: 10.0, max: 25.0 },
    dissolved_oxygen: { min: 6.0, max: 14.0 },
    orp: { min: 600, max: 850 },
    chlorine: { min: 0.2, max: 2.0 },
    nitrate: { min: 0.0, max: 10.0 }
  },
  aquaculture: {
    pH: { min: 6.8, max: 8.2 },
    turbidity: { min: 5.0, max: 25.0 },
    tds: { min: 100, max: 1200 },
    temperature: { min: 20.0, max: 28.0 },
    dissolved_oxygen: { min: 5.5, max: 10.0 },
    orp: { min: 250, max: 450 },
    chlorine: { min: 0.0, max: 0.05 },
    nitrate: { min: 0.0, max: 5.0 }
  },
  agriculture: {
    pH: { min: 6.0, max: 8.5 },
    turbidity: { min: 0.0, max: 50.0 },
    tds: { min: 100, max: 1500 },
    temperature: { min: 15.0, max: 30.0 },
    dissolved_oxygen: { min: 4.0, max: 12.0 },
    orp: { min: 200, max: 600 },
    chlorine: { min: 0.0, max: 1.0 },
    nitrate: { min: 0.0, max: 30.0 }
  },
  industrial: {
    pH: { min: 6.0, max: 9.0 },
    turbidity: { min: 0.0, max: 20.0 },
    tds: { min: 10, max: 1000 },
    temperature: { min: 10.0, max: 35.0 },
    dissolved_oxygen: { min: 3.0, max: 14.0 },
    orp: { min: 200, max: 700 },
    chlorine: { min: 0.0, max: 3.0 },
    nitrate: { min: 0.0, max: 40.0 }
  },
  recreational: {
    pH: { min: 7.2, max: 7.8 },
    turbidity: { min: 0.0, max: 5.0 },
    tds: { min: 100, max: 1500 },
    temperature: { min: 22.0, max: 30.0 },
    dissolved_oxygen: { min: 5.0, max: 12.0 },
    orp: { min: 650, max: 800 },
    chlorine: { min: 1.0, max: 3.0 },
    nitrate: { min: 0.0, max: 10.0 }
  }
};
